# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hub.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\"%\n\x07\x43ommand\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t25\n\x12\x43\x61lculationService\x12\x1f\n\tCalculate\x12\x08.Command\x1a\x08.CommandB\x12\n\x10student.examplesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020student.examples'
  _globals['_COMMAND']._serialized_start=13
  _globals['_COMMAND']._serialized_end=50
  _globals['_CALCULATIONSERVICE']._serialized_start=52
  _globals['_CALCULATIONSERVICE']._serialized_end=105
# @@protoc_insertion_point(module_scope)
